// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncdeigthcuorahcgnfqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jZGVpZ3RoY3VvcmFoY2duZnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTM2NTMsImV4cCI6MjA2MTc2OTY1M30.p_gpgaow2vtofMWadAIby_lG3yNsW8ormXV8xzpKjdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);